
package com.atguigu.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWsImpService", targetNamespace = "http://ws.atguigu.com/", wsdlLocation = "http://192.168.13.34:5555/ws?wsdl")
public class TestWsImpService
    extends Service
{

    private final static URL TESTWSIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWSIMPSERVICE_EXCEPTION;
    private final static QName TESTWSIMPSERVICE_QNAME = new QName("http://ws.atguigu.com/", "TestWsImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.13.34:5555/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWSIMPSERVICE_WSDL_LOCATION = url;
        TESTWSIMPSERVICE_EXCEPTION = e;
    }

    public TestWsImpService() {
        super(__getWsdlLocation(), TESTWSIMPSERVICE_QNAME);
    }

    public TestWsImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWSIMPSERVICE_QNAME, features);
    }

    public TestWsImpService(URL wsdlLocation) {
        super(wsdlLocation, TESTWSIMPSERVICE_QNAME);
    }

    public TestWsImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWSIMPSERVICE_QNAME, features);
    }

    public TestWsImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWsImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWsImp
     */
    @WebEndpoint(name = "TestWsImpPort")
    public TestWsImp getTestWsImpPort() {
        return super.getPort(new QName("http://ws.atguigu.com/", "TestWsImpPort"), TestWsImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWsImp
     */
    @WebEndpoint(name = "TestWsImpPort")
    public TestWsImp getTestWsImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.atguigu.com/", "TestWsImpPort"), TestWsImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWSIMPSERVICE_EXCEPTION!= null) {
            throw TESTWSIMPSERVICE_EXCEPTION;
        }
        return TESTWSIMPSERVICE_WSDL_LOCATION;
    }

}
